# Generated by Django 6.0.7 on 2026-07-20 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='store',
        ),
        migrations.RemoveField(
            model_name='order',
            name='store',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
