# Generated by Django 6.0.7 on 2026-07-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0002_remove_product_store_remove_order_store_delete_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.JSONField(default=list, verbose_name='Danh sách sản phẩm mua'),
        ),
    ]
