# Generated by Django 6.0.7 on 2026-07-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0003_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('thoi-trang', 'Thời trang'), ('dien-tu', 'Điện tử'), ('gia-dung', 'Gia dụng'), ('sach-truyen', 'Sách & Truyện')], default='thoi-trang', max_length=50, verbose_name='Danh mục'),
        ),
    ]
