# Generated by Django 6.0.7 on 2026-07-20 07:36

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0004_product_category'),
    ]

    operations = [
        UnaccentExtension(),
    ]
