# Generated by Django 6.0.7 on 2026-07-24 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0005_enable_unaccent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, verbose_name='Thông số kỹ thuật'),
        ),
    ]
