# Generated by Django 6.0.7 on 2026-07-24 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0007_alter_product_specifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Khóa cấu hình')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Dữ liệu')),
            ],
            options={
                'verbose_name': 'Cấu hình trang',
                'verbose_name_plural': 'Cấu hình trang',
            },
        ),
    ]
