# Generated by Django 6.0.7 on 2026-07-24 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0008_siteconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', models.TextField(blank=True, verbose_name='Giới thiệu đơn vị')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Địa chỉ')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('working_hours', models.CharField(blank=True, max_length=200, verbose_name='Giờ làm việc')),
                ('social_links', models.JSONField(blank=True, default=list, verbose_name='Mạng xã hội')),
                ('partners', models.JSONField(blank=True, default=list, verbose_name='Đối tác')),
                ('footer_links', models.JSONField(blank=True, default=list, verbose_name='Liên kết footer')),
                ('copyright_text', models.CharField(blank=True, max_length=500, verbose_name='Copyright')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='footer/', verbose_name='Logo footer')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footer',
            },
        ),
    ]
