# Generated by Django 6.0.7 on 2026-07-24 06:52

from django.db import migrations, models
import json


def convert_specs_text_to_json(apps, schema_editor):
    """Chuyển dữ liệu specifications từ text cũ sang JSON string hợp lệ (trước khi alter field)"""
    Product = apps.get_model('core_api', 'Product')
    for product in Product.objects.all():
        old_specs = product.specifications
        if isinstance(old_specs, str) and old_specs.strip():
            lines = old_specs.strip().split('\n')
            new_specs = []
            for line in lines:
                line = line.strip()
                if ':' in line:
                    key, value = line.split(':', 1)
                    new_specs.append({
                        'key': key.strip(),
                        'value': value.strip()
                    })
                elif line:
                    new_specs.append({
                        'key': line,
                        'value': ''
                    })
            # Ghi lại dưới dạng JSON string (text) để PostgreSQL chấp nhận khi alter
            product.specifications = json.dumps(new_specs, ensure_ascii=False)
        elif not old_specs or old_specs == '' or old_specs is None:
            product.specifications = '[]'
        product.save(update_fields=['specifications'])


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0009_footer'),
    ]

    operations = [
        # Bước 1: Chuyển dữ liệu text cũ thành JSON string hợp lệ TRƯỚC khi alter field
        migrations.RunPython(convert_specs_text_to_json),
        # Bước 2: Đổi tên label description
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Mô tả sản phẩm (hỗ trợ Markdown)'),
        ),
        # Bước 3: Alter field từ TextField → JSONField (dữ liệu đã là JSON string hợp lệ)
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.JSONField(blank=True, default=list, verbose_name='Thông số kỹ thuật (JSON key-value)'),
        ),
    ]
