# Generated by Django 6.0.7 on 2026-08-04 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0011_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=10, verbose_name='Số điện thoại'),
        ),
    ]
