# Generated by Django 6.0.7 on 2026-08-06 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0015_product_is_active_product_stock_pagevisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.JSONField(blank=True, default=list, verbose_name='Danh sách ảnh sản phẩm (tối đa 5)'),
        ),
    ]
