# Generated by Django 6.0.7 on 2026-08-06 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0016_product_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Ảnh 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Ảnh 3'),
        ),
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Ảnh 4'),
        ),
        migrations.AddField(
            model_name='product',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Ảnh 5'),
        ),
    ]
