# Generated by Django 6.0.7 on 2026-08-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0017_remove_product_images_product_image2_product_image3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, verbose_name='Ghi chú đơn hàng'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Địa chỉ giao hàng'),
        ),
    ]
