# Generated by Django 6.0.7 on 2026-08-06 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0018_order_note_userprofile_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Hồ sơ người dùng', 'verbose_name_plural': 'Hồ sơ người dùng'},
        ),
    ]
