# Generated by Django 6.0.7 on 2026-08-06 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0019_alter_userprofile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'UserProfile', 'verbose_name_plural': 'UserProfile'},
        ),
    ]
