# Generated by Django 6.0.7 on 2026-08-06 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0020_alter_userprofile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagevisit',
            options={'ordering': ['-viewed_at'], 'verbose_name': 'PageVisit', 'verbose_name_plural': 'PageVisit'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Review', 'verbose_name_plural': 'Review'},
        ),
    ]
