# Generated by Django 6.0.7 on 2026-08-07 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0022_userprofile_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('CUSTOMER', 'Khách hàng'), ('STAFF', 'Nhân viên/Admin')], max_length=20, null=True, verbose_name='Hủy bởi'),
        ),
    ]
