# Generated by Django 6.0.7 on 2026-08-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0025_product_category_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Mã sản phẩm (SKU)'),
        ),
    ]
