# Generated by Django 6.0.7 on 2026-08-08 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0026_product_sku'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Category'},
        ),
    ]
