# Generated by Django 6.0.7 on 2026-08-08 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0027_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='footer_links',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='partners',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='social_links',
        ),
        migrations.AddField(
            model_name='footer',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='footer',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='footer',
            name='tiktok_url',
            field=models.URLField(blank=True, verbose_name='TikTok'),
        ),
        migrations.AddField(
            model_name='footer',
            name='youtube_url',
            field=models.URLField(blank=True, verbose_name='YouTube'),
        ),
        migrations.AddField(
            model_name='footer',
            name='zalo_url',
            field=models.URLField(blank=True, verbose_name='Zalo'),
        ),
    ]
