# Generated by Django 6.0.7 on 2026-08-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0028_remove_footer_footer_links_remove_footer_partners_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='contact_content',
            field=models.TextField(blank=True, verbose_name='Nội dung Liên hệ'),
        ),
        migrations.AddField(
            model_name='footer',
            name='intro_content',
            field=models.TextField(blank=True, verbose_name='Nội dung Giới thiệu'),
        ),
        migrations.AddField(
            model_name='footer',
            name='privacy_content',
            field=models.TextField(blank=True, verbose_name='Nội dung Chính sách bảo mật'),
        ),
        migrations.AddField(
            model_name='footer',
            name='return_content',
            field=models.TextField(blank=True, verbose_name='Nội dung Chính sách đổi trả'),
        ),
        migrations.AddField(
            model_name='footer',
            name='shipping_content',
            field=models.TextField(blank=True, verbose_name='Nội dung Chính sách vận chuyển'),
        ),
        migrations.AddField(
            model_name='footer',
            name='warranty_content',
            field=models.TextField(blank=True, verbose_name='Nội dung Chính sách bảo hành'),
        ),
    ]
